services:
  postgres:
    image: postgres:16.4-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - "5436:5432"
    # ports:
    #   - "${POSTGRES_PORT_MAPPING:-5433:5432}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - coolify

networks:
  coolify:
    external: true
    name: fixeo-network
