services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres_fixeo
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT_MAPPING:-5433:5432}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
